import { useState, useEffect } from "react";
import Sidebar from "../Components/Sidebar";
import { FaClock, FaCalendarAlt } from "react-icons/fa";

export default function FacultyDashboard() {
    const [timetables, setTimetables] = useState([]);
    const [selectedTimetable, setSelectedTimetable] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchTimetables();
    }, []);

    const fetchTimetables = async () => {
        try {
            const token = localStorage.getItem("token");
            const department = localStorage.getItem("department");

            const res = await fetch("/api/timetables", {
                headers: { "Authorization": `Bearer ${token}` }
            });
            const data = await res.json();

            // Filter to only show timetables for this faculty's department
            const filtered = Array.isArray(data) && department
                ? data.filter(t => t.department === department)
                : (Array.isArray(data) ? data : []);

            setTimetables(filtered);
            if (filtered.length > 0) {
                setSelectedTimetable(filtered[0]);
            }
        } catch (error) {
            console.error("Error fetching timetables:", error);
        } finally {
            setLoading(false);
        }
    };

    const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];

    return (
        <div className="app-container">
            <Sidebar />
            <main className="main-content">
                <header className="page-header">
                    <h1 className="page-title">Faculty Dashboard</h1>
                </header>

                {/* Welcome Card */}
                <div className="glass-panel" style={{ padding: "2rem", marginBottom: "2rem" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
                        <div style={{
                            background: "rgba(139, 92, 246, 0.2)",
                            padding: "1rem",
                            borderRadius: "12px",
                            fontSize: "2rem",
                            color: "rgb(139, 92, 246)"
                        }}>
                            <FaCalendarAlt />
                        </div>
                        <div>
                            <h2 style={{ margin: 0 }}>Welcome, Faculty Member</h2>
                            <p style={{ margin: "0.5rem 0 0 0", color: "var(--text-muted)" }}>
                                View your assigned timetables and schedules below
                            </p>
                        </div>
                    </div>
                </div>

                {/* Timetable Selection */}
                {timetables.length > 0 && (
                    <div style={{ marginBottom: "1.5rem" }}>
                        <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: 500 }}>
                            Select Timetable:
                        </label>
                        <select
                            className="input-field"
                            value={selectedTimetable?._id || ""}
                            onChange={(e) => {
                                const tt = timetables.find(t => t._id === e.target.value);
                                setSelectedTimetable(tt);
                            }}
                            style={{ maxWidth: "400px" }}
                        >
                            {timetables.map((tt) => (
                                <option key={tt._id} value={tt._id}>
                                    {tt.name} - {tt.department} (Sem {tt.semester})
                                </option>
                            ))}
                        </select>
                    </div>
                )}

                {/* Timetable Display */}
                {loading ? (
                    <div className="glass-panel" style={{ padding: "2rem", textAlign: "center" }}>
                        <p>Loading timetables...</p>
                    </div>
                ) : timetables.length === 0 ? (
                    <div className="glass-panel" style={{ padding: "2rem", textAlign: "center" }}>
                        <FaClock style={{ fontSize: "3rem", color: "var(--text-muted)", marginBottom: "1rem" }} />
                        <h3>No Timetables Available</h3>
                        <p style={{ color: "var(--text-muted)" }}>
                            Timetables will appear here once they are generated by the admin.
                        </p>
                    </div>
                ) : selectedTimetable ? (
                    <div className="glass-panel" style={{ padding: "1.5rem", overflowX: "auto" }}>
                        <h2 style={{ marginTop: 0 }}>{selectedTimetable.name}</h2>
                        <table style={{
                            width: "100%",
                            borderCollapse: "collapse",
                            marginTop: "1rem"
                        }}>
                            <thead>
                                <tr style={{ background: "rgba(255,255,255,0.05)" }}>
                                    <th style={{ padding: "1rem", textAlign: "left", borderBottom: "1px solid var(--glass-border)" }}>
                                        Time
                                    </th>
                                    {DAYS.map(day => (
                                        <th key={day} style={{ padding: "1rem", textAlign: "left", borderBottom: "1px solid var(--glass-border)" }}>
                                            {day}
                                        </th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody>
                                {selectedTimetable.schedule && selectedTimetable.schedule.length > 0 ? (
                                    (() => {
                                        const allTimes = new Set();
                                        selectedTimetable.schedule.forEach(daySchedule => {
                                            daySchedule.slots?.forEach(slot => allTimes.add(slot.time));
                                        });
                                        const sortedTimes = Array.from(allTimes).sort();

                                        return sortedTimes.map(time => (
                                            <tr key={time}>
                                                <td style={{ padding: "1rem", borderBottom: "1px solid var(--glass-border)", fontWeight: 500 }}>
                                                    {time}
                                                </td>
                                                {DAYS.map(day => {
                                                    const daySchedule = selectedTimetable.schedule.find(d => d.day === day);
                                                    const slot = daySchedule?.slots?.find(s => s.time === time);

                                                    return (
                                                        <td key={day} style={{ padding: "1rem", borderBottom: "1px solid var(--glass-border)" }}>
                                                            {slot ? (
                                                                <div style={{
                                                                    background: "rgba(79, 70, 229, 0.1)",
                                                                    padding: "0.5rem",
                                                                    borderRadius: "6px",
                                                                    borderLeft: "3px solid rgb(79, 70, 229)"
                                                                }}>
                                                                    <div style={{ fontWeight: 600 }}>
                                                                        {slot.subject?.name || "N/A"}
                                                                    </div>
                                                                    <small style={{ color: "var(--text-muted)" }}>
                                                                        {slot.classroom?.name || "TBA"}
                                                                    </small>
                                                                </div>
                                                            ) : (
                                                                <span style={{ color: "var(--text-muted)" }}>-</span>
                                                            )}
                                                        </td>
                                                    );
                                                })}
                                            </tr>
                                        ));
                                    })()
                                ) : (
                                    <tr>
                                        <td colSpan={6} style={{ padding: "2rem", textAlign: "center", color: "var(--text-muted)" }}>
                                            No schedule data available
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                ) : null}
            </main>
        </div>
    );
}
